# Generated by Django 5.2.8 on 2025-11-06 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatTipoCuenta',
            fields=[
                ('id_tipo_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_comment="Código único para el tipo de cuenta, ej: 'CTA_CTE', 'AHORRO'", max_length=20, unique=True)),
                ('nombre', models.CharField(db_comment="Nombre descriptivo, ej: 'Cuenta Corriente'", max_length=60)),
            ],
            options={
                'verbose_name': 'Catálogo: Tipo de Cuenta Bancaria',
                'verbose_name_plural': 'Catálogo: Tipos de Cuenta Bancaria',
                'db_table': 'cat_tipo_cuenta',
            },
        ),
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id_condominio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_comment='Nombre oficial y único del condominio', max_length=120, unique=True)),
                ('rut_base', models.IntegerField(blank=True, db_comment='RUT del condominio (sin DV)', null=True)),
                ('rut_dv', models.CharField(blank=True, db_comment='Dígito verificador del RUT', max_length=1, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('comuna', models.CharField(blank=True, max_length=80, null=True)),
                ('region', models.CharField(blank=True, max_length=80, null=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=120, null=True)),
                ('telefono', models.CharField(blank=True, max_length=40, null=True)),
                ('banco', models.CharField(blank=True, max_length=80, null=True)),
                ('num_cuenta', models.CharField(blank=True, max_length=40, null=True)),
                ('id_tipo_cuenta', models.ForeignKey(blank=True, db_column='id_tipo_cuenta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cattipocuenta', verbose_name='Tipo de Cuenta')),
            ],
            options={
                'verbose_name': 'Condominio',
                'verbose_name_plural': 'Condominios',
                'db_table': 'condominio',
            },
        ),
    ]
