# Generated by Django 5.2.8 on 2025-11-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_catplan_suscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatSegmento',
            fields=[
                ('id_segmento', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Catálogo: Segmento de Unidad',
                'verbose_name_plural': 'Catálogo: Segmentos de Unidad',
                'db_table': 'cat_segmento',
            },
        ),
        migrations.CreateModel(
            name='CatUnidadTipo',
            fields=[
                ('id_unidad_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Catálogo: Tipo de Unidad',
                'verbose_name_plural': 'Catálogo: Tipos de Unidad',
                'db_table': 'cat_unidad_tipo',
            },
        ),
        migrations.CreateModel(
            name='CatViviendaSubtipo',
            fields=[
                ('id_viv_subtipo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Catálogo: Subtipo de Vivienda',
                'verbose_name_plural': 'Catálogo: Subtipos de Vivienda',
                'db_table': 'cat_vivienda_subtipo',
            },
        ),
    ]
