# Generated by Django 5.2.8 on 2025-11-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_catsegmento_catunidadtipo_catviviendasubtipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='catplan',
            name='max_grupos',
            field=models.PositiveSmallIntegerField(default=3, help_text='Número máximo de grupos (torres, etapas) permitidos'),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='max_grupos',
            field=models.PositiveSmallIntegerField(default=3, help_text='Límite real de grupos (torres, etapas) para ESTA suscripción'),
        ),
    ]
