# Generated by Django 5.2.8 on 2025-11-10 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_catplan_max_grupos_suscripcion_max_grupos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('tipo', models.CharField(db_comment="Tipo de grupo, ej: 'Torre', 'Etapa', 'Sector'", max_length=45)),
                ('id_condominio', models.ForeignKey(db_column='id_condominio', on_delete=django.db.models.deletion.RESTRICT, to='core.condominio')),
            ],
            options={
                'verbose_name': 'Grupo (Torre/Etapa)',
                'verbose_name_plural': 'Grupos (Torres/Etapas)',
                'db_table': 'grupo',
                'unique_together': {('id_condominio', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id_unidad', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_comment="Código/Nro de la unidad, ej: 'DEPTO-101', 'BOD-01', 'EST-12'", max_length=40)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('anexo_incluido', models.BooleanField(default=False)),
                ('anexo_cobrable', models.BooleanField(default=False)),
                ('rol_sii', models.CharField(blank=True, max_length=40, null=True)),
                ('metros2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coef_prop', models.DecimalField(db_comment='Coeficiente de propiedad (alícuota)', decimal_places=6, max_digits=8)),
                ('habitable', models.BooleanField(default=True)),
                ('id_grupo', models.ForeignKey(blank=True, db_column='id_grupo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.grupo', verbose_name='Grupo (Torre/Etapa)')),
                ('id_segmento', models.ForeignKey(blank=True, db_column='id_segmento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.catsegmento', verbose_name='Segmento')),
                ('id_unidad_tipo', models.ForeignKey(blank=True, db_column='id_unidad_tipo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.catunidadtipo', verbose_name='Tipo de Unidad')),
                ('id_viv_subtipo', models.ForeignKey(blank=True, db_column='id_viv_subtipo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.catviviendasubtipo', verbose_name='Subtipo de Vivienda')),
            ],
            options={
                'verbose_name': 'Unidad (Depto/Casa)',
                'verbose_name_plural': 'Unidades (Deptos/Casas)',
                'db_table': 'unidad',
                'unique_together': {('id_grupo', 'codigo')},
            },
        ),
    ]
