# Generated by Django 5.2.8 on 2025-11-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_grupo_unidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatDocTipo',
            fields=[
                ('id_doc_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(default='', max_length=60)),
            ],
            options={
                'verbose_name': 'Catálogo: Tipo de Documento',
                'verbose_name_plural': 'Catálogo: Tipos de Documento',
                'db_table': 'cat_doc_tipo',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('persona', 'Persona'), ('empresa', 'Empresa')], default='empresa', max_length=10)),
                ('rut_base', models.IntegerField()),
                ('rut_dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=140)),
                ('giro', models.CharField(blank=True, max_length=140, null=True)),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
                ('telefono', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'unique_together': {('rut_base', 'rut_dv')},
            },
        ),
    ]
