# Generated by Django 5.2.8 on 2025-11-19 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_catdoctipo_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoCategoria',
            fields=[
                ('id_gasto_categ', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría de Gasto',
                'verbose_name_plural': 'Categorías de Gastos',
                'db_table': 'gasto_categoria',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id_gasto', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(help_text='Periodo contable formato YYYYMM (ej: 202511)', max_length=6)),
                ('documento_folio', models.CharField(blank=True, max_length=40, null=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_venc', models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento')),
                ('neto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('evidencia_url', models.URLField(blank=True, max_length=500, null=True)),
                ('id_condominio', models.ForeignKey(db_column='id_condominio', on_delete=django.db.models.deletion.RESTRICT, to='core.condominio')),
                ('id_doc_tipo', models.ForeignKey(blank=True, db_column='id_doc_tipo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.catdoctipo', verbose_name='Tipo Documento')),
                ('id_proveedor', models.ForeignKey(blank=True, db_column='id_proveedor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.proveedor', verbose_name='Proveedor')),
                ('id_gasto_categ', models.ForeignKey(db_column='id_gasto_categ', on_delete=django.db.models.deletion.RESTRICT, to='core.gastocategoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'db_table': 'gasto',
                'indexes': [models.Index(fields=['id_condominio', 'periodo'], name='ix_gasto_periodo')],
            },
        ),
    ]
