# Generated by Django 5.2.8 on 2025-11-21 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_trabajador_trabajadorcontrato_remuneracion"),
    ]

    operations = [
        migrations.CreateModel(
            name="InteresRegla",
            fields=[
                (
                    "id_interes_regla",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("vigente_desde", models.DateField()),
                ("vigente_hasta", models.DateField(blank=True, null=True)),
                (
                    "tasa_anual_pct",
                    models.DecimalField(
                        decimal_places=3, max_digits=6, verbose_name="Tasa Anual %"
                    ),
                ),
                ("dias_gracia", models.PositiveSmallIntegerField(default=0)),
                ("fuente_url", models.CharField(blank=True, max_length=300, null=True)),
                ("comentario", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "id_condominio",
                    models.ForeignKey(
                        db_column="id_condominio",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.condominio",
                    ),
                ),
                (
                    "id_segmento",
                    models.ForeignKey(
                        db_column="id_segmento",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.catsegmento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regla de Interés",
                "verbose_name_plural": "Reglas de Interés",
                "db_table": "interes_regla",
                "indexes": [
                    models.Index(
                        fields=[
                            "id_condominio",
                            "id_segmento",
                            "vigente_desde",
                            "vigente_hasta",
                        ],
                        name="ix_ir_rango",
                    )
                ],
            },
        ),
    ]
