# Generated by Django 5.2.8 on 2025-11-21 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_interesregla"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParamReglamento",
            fields=[
                (
                    "id_condominio",
                    models.OneToOneField(
                        db_column="id_condominio",
                        on_delete=django.db.models.deletion.RESTRICT,
                        primary_key=True,
                        serialize=False,
                        to="core.condominio",
                    ),
                ),
                (
                    "recargo_fondo_reserva_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        max_digits=5,
                        verbose_name="Recargo Fondo Reserva %",
                    ),
                ),
                (
                    "interes_mora_anual_pct",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ("dias_gracia", models.PositiveSmallIntegerField(default=0)),
                (
                    "multa_morosidad_fija",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Parámetros de Reglamento",
                "verbose_name_plural": "Parámetros de Reglamentos",
                "db_table": "param_reglamento",
            },
        ),
        migrations.CreateModel(
            name="FondoReservaMov",
            fields=[
                (
                    "id_fondo_reserva",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("fecha", models.DateTimeField()),
                ("tipo", models.CharField(max_length=10)),
                ("periodo", models.CharField(blank=True, max_length=6, null=True)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("glosa", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "id_condominio",
                    models.ForeignKey(
                        db_column="id_condominio",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.condominio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento Fondo Reserva",
                "verbose_name_plural": "Movimientos Fondo Reserva",
                "db_table": "fondo_reserva_mov",
                "indexes": [
                    models.Index(fields=["id_condominio", "fecha"], name="ix_fr")
                ],
            },
        ),
    ]
