# Generated by Django 5.2.8 on 2025-11-21 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_paramreglamento_fondoreservamov"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Auditoria",
            fields=[
                ("id_auditoria", models.AutoField(primary_key=True, serialize=False)),
                ("entidad", models.CharField(max_length=40)),
                ("entidad_id", models.BigIntegerField()),
                ("accion", models.CharField(max_length=10)),
                (
                    "usuario_email",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("detalle", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_usuario",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_usuario",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Auditoría",
                "verbose_name_plural": "Auditoría del Sistema",
                "db_table": "auditoria",
            },
        ),
        migrations.CreateModel(
            name="CondominioAnexoRegla",
            fields=[
                ("id_regla", models.AutoField(primary_key=True, serialize=False)),
                (
                    "anexo_tipo",
                    models.CharField(
                        choices=[
                            ("bodega", "Bodega"),
                            ("estacionamiento", "Estacionamiento"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "incluido_qty",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Cant. Incluida"
                    ),
                ),
                (
                    "cobrable_por_sobre_qty",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Cobrable si excede"
                    ),
                ),
                ("vigente_desde", models.DateField()),
                ("vigente_hasta", models.DateField(blank=True, null=True)),
                ("comentario", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "id_condominio",
                    models.ForeignKey(
                        db_column="id_condominio",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.condominio",
                    ),
                ),
                (
                    "id_viv_subtipo",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_viv_subtipo",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.catviviendasubtipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regla de Anexo (Bodega/Estac)",
                "verbose_name_plural": "Reglas de Anexos",
                "db_table": "condominio_anexo_regla",
                "indexes": [
                    models.Index(
                        fields=[
                            "id_condominio",
                            "id_viv_subtipo",
                            "anexo_tipo",
                            "vigente_desde",
                            "vigente_hasta",
                        ],
                        name="ix_car_rango",
                    )
                ],
            },
        ),
    ]
