# Generated by Django 5.2.8 on 2025-11-21 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_auditoria_condominioanexoregla"),
    ]

    operations = [
        migrations.CreateModel(
            name="CuentaContable",
            fields=[
                (
                    "id_cta_contable",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("codigo", models.CharField(max_length=40, unique=True)),
                ("nombre", models.CharField(max_length=80)),
            ],
            options={
                "verbose_name": "Cuenta Contable",
                "verbose_name_plural": "Cuentas Contables",
                "db_table": "cuenta_contable",
            },
        ),
        migrations.CreateModel(
            name="LibroMovimiento",
            fields=[
                ("id_libro_mov", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateTimeField()),
                (
                    "debe",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "haber",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("ref_tabla", models.CharField(blank=True, max_length=40, null=True)),
                ("ref_id", models.BigIntegerField(blank=True, null=True)),
                ("glosa", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "id_condominio",
                    models.ForeignKey(
                        db_column="id_condominio",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.condominio",
                    ),
                ),
                (
                    "id_cta_contable",
                    models.ForeignKey(
                        db_column="id_cta_contable",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.cuentacontable",
                    ),
                ),
            ],
            options={
                "db_table": "libro_movimiento",
                "indexes": [
                    models.Index(
                        fields=["id_condominio", "fecha", "id_cta_contable"],
                        name="ix_mayor",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ResumenMensual",
            fields=[
                ("id_resumen", models.AutoField(primary_key=True, serialize=False)),
                ("periodo", models.CharField(max_length=6)),
                (
                    "total_gastos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_cargos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_interes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_descuentos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_pagado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "saldo_por_cobrar",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("generado_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_condominio",
                    models.ForeignKey(
                        db_column="id_condominio",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.condominio",
                    ),
                ),
            ],
            options={
                "db_table": "resumen_mensual",
                "unique_together": {("id_condominio", "periodo")},
            },
        ),
    ]
