# Generated by Django 5.2.8 on 2025-11-21 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_cuentacontable_libromovimiento_resumenmensual"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id_notificacion",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("mensaje", models.TextField()),
                ("leido", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "db_table": "notificacion",
                "ordering": ["-created_at"],
            },
        ),
    ]
