# Generated by Django 5.2.8 on 2025-11-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_notificacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="gasto",
            name="estado_validacion",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("aprobado", "Aprobado"),
                    ("rechazado", "Rechazado"),
                ],
                db_comment="Estado de validación del gasto (doble ciego)",
                default="pendiente",
                max_length=20,
            ),
        ),
    ]
