# Generated by Django 5.2.8 on 2025-11-22 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_gasto_estado_validacion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="suscripcion",
            name="id_usuario",
            field=models.OneToOneField(
                db_column="id_usuario",
                help_text="El usuario (administrador) dueño de esta suscripción",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
