# Generated by Django 5.2.8 on 2025-11-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_suscripcion_id_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catplan",
            name="max_unidades",
            field=models.PositiveSmallIntegerField(
                default=50, help_text="Número máximo de unidades (deptos/casas) totales"
            ),
        ),
    ]
