# Generated by Django 5.2.8 on 2025-11-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_catplan_max_unidades"),
    ]

    operations = [
        migrations.AddField(
            model_name="condominio",
            name="color_primario",
            field=models.CharField(
                default="#0d6efd", help_text="Color hexadecimal principal", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="condominio",
            name="color_secundario",
            field=models.CharField(
                default="#6c757d",
                help_text="Color hexadecimal secundario",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="condominio",
            name="logo_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
