# Generated by Django 5.2.8 on 2025-11-21 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_copropietario_residencia"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodigoVerificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=6)),
                ("accion", models.CharField(max_length=50)),
                ("creado_at", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Código de Verificación",
                "verbose_name_plural": "Códigos de Verificación",
                "db_table": "codigo_verificacion",
            },
        ),
    ]
